services:
    php:
        build: ./docker/php
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    db:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - laravel

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
        driver: local
